### ISSUE TITLE
Ionic v3 Support

### ISSUE THREAD

**Issue by maikforte** [rossmartin/cordova-plugin-ios-detect-screenshot#2]
I was wondering if this plugin has been tested on Ionic as well.

I tried both approaches but none of them is firing

Approach 1:
```
import { Events } from 'ionic-angular';
...
this.events.subscribe('screenshotDidTake', () => {
    console.log('screenshotDidTake');
});
```

Approach 2:
```
declare let window;
...
window.addEventListener('screenshotDidTake', function() {
    console.log('screenshotDidTake');
}, false);
```

**Comment by maikforte** [comment]
Approach 2 works on Ionic v3.

It's odd that it's not working on an emulator but works really well with native device

**Comment by rossmartin** [comment]
@maikforte Sorry I wasn't able to get to this earlier.  Thanks for the update - you remind me that I should mention that it does not work for the simulator.
